server:
  servlet: 
    encoding: 
      charset: utf-8
      enabled: true

spring:
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    # local
#    url: jdbc:mysql://localhost:3306/book?serverTimezone=Asia/Seoul
#    username: root
#    password: 11111111
    
    # dev
#    url: jdbc:mysql://book.cxmywrhxhdno.ap-northeast-2.rds.amazonaws.com:3306/book?serverTimezone=Asia/Seoul
#    username: root
#    password: 11111111

    # k8s-node1
#    url: jdbc:mysql://192.168.56.31:30002/book?serverTimezone=Asia/Seoul
#    username: root
#    password: root1234

    # k8s-node2
    url: jdbc:mysql://192.168.56.32:30002/book?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  
  jpa: 
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true